### ISSUE TITLE
Compatibility - Excalidraw - Galaxy Browser

### ISSUE THREAD

**Issue by 7flash** [louis030195/obsidian-ava#10]
Re: Excalibrain OpenAI Script: https://github.com/zsviczian/obsidian-excalidraw-plugin/pull/833

Re: Galaxy Browser: https://www.youtube.com/watch?v=8Y7_gvmMyKY

**Comment by louis030195** [comment]
?

**Comment by 7flash** [comment]
https://github.com/excalidraw/excalidraw/issues/7257
