### ISSUE TITLE
Inability to save API key

### ISSUE THREAD

**Issue by TSSlade** [louis030195/obsidian-ava#11]
The settings interface of the plugin will not accept OpenAI API keys:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/3211478/197374071-bbae9b5a-164b-4b42-8912-d0339da1db63.png">

Is there some kind of workaround? Or a way of understanding what the plugin is expecting of the API key?

**Comment by louis030195** [comment]
Try with your organization ID (not name)

![image](https://user-images.githubusercontent.com/25003283/197389725-c065307c-bfce-432f-a0bc-976ed9978aca.png)

**Comment by louis030195** [comment]
https://beta.openai.com/account/org-settings
