### ISSUE TITLE
Error with Stable Diffusion Image Generation

### ISSUE THREAD

**Issue by sudheer82** [louis030195/obsidian-ava#12]
Following is the detail. Unable to generate images
I have a valid API key and able to test @ [https://beta.dreamstudio.ai/](https://beta.dreamstudio.ai/)

## Prompt Selection used

> A man is playing chess against a robot, the robot is winning and the man is getting frustrated, the robot is taunting the man and the man is getting angry, the man is about to lose the game, 8k resolution, post processing, detailed, robot, chess, man, game, losing, frustrated, angry, taunting, red eyes, grinning face, plans, announcement, dismal, 8k

From command Palette, Select

**Obsidian ava: Generate an image based on selected text** 
Using Hotkeys: `Ctrl + Alt + S`

## Error
```
Error while generating image
TypeError: Cannot read properties of undefined (reading filePath)
```

## Status bar warning
![image](https://user-images.githubusercontent.com/3577158/201538681-a836eefa-c604-49a3-a759-0d9eff5305fe.png)

**On hover message**
![image](https://user-images.githubusercontent.com/3577158/201538620-acf82e72-d45f-4697-860c-d7423c080572.png)

## Versions

OS: Windows 10
Obsidian ava Version: 1.0.8
Obsidian version: v1.O.3

**Comment by louis030195** [comment]
@sudheer82 

Basically there is no error handling currently in obsidian-ava, so maybe it's failing here

https://github.com/louis030195/obsidian-ava/blob/ef3c5e74eb68c965400174abe85e8cd3565ae749/main.tsx#L81

Do you still have credit? Have internet? Open Obsidian console (option + command + i on Mac, probably alt+windows+i on Windows) please and share what's written in the console.

PS: don't email me for GitHub issues please

**Comment by sudheer82** [comment]
@louis030195 - thanks for the quick response. below is the console.log

```
plugin:ava:52916 {isOk: false, status: 'Unknown', code: 2, message: 'Response closed without headers', trailers: e4}code: 2isOk: falsemessage: "Response closed without headers"status: "Unknown"trailers: e4headersMap: {}[[Prototype]]: Objectappend: ƒ (e5, t4)appendFromString: ƒ (e5)delete: ƒ (e5, t4)forEach: ƒ (e5)get: ƒ (e5)has: ƒ (e5, t4)set: ƒ (e5, t4)toHeaders: ƒ ()constructor: ƒ e4(e5, t4)[[Prototype]]: Object[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
eval @ plugin:ava:52916
emit @ node:events:390
onEnd @ plugin:ava:52879
eval @ plugin:ava:25159
e3.rawOnError @ plugin:ava:25156
e3.onTransportEnd @ plugin:ava:25117
eval @ plugin:ava:25614
emit @ node:events:390
socketErrorListener @ node:_http_client:447
emit @ node:events:390
emitErrorNT @ node:internal/streams/destroy:157
emitErrorCloseNT @ node:internal/streams/destroy:122
processTicksAndRejections @ node:internal/process/task_queues:83
```

**Comment by sudheer82** [comment]
@louis030195 - any suggestions on what could be the issue?

**Comment by sudheer82** [comment]
Console log with 1.1.0 release. 

```js
{isOk: false, status: 'Unknown', code: 2, message: 'Response closed without headers', trailers: e5}
code: 2
isOk: false
message: "Response closed without headers"
status: "Unknown"
trailers: e5
headersMap: {}
[[Prototype]]: Object
[[Prototype]]: Object
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
__proto__: (...)
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
```

Status bar error message

<img src="https://user-images.githubusercontent.com/3577158/205487625-526be21b-14b7-421d-a9b6-07b7b1b9fc68.png" width="200">

**Comment by louis030195** [comment]
Please try new versions - completely different setup & LMK
