### ISSUE TITLE
API key is not recognize

### ISSUE THREAD

**Issue by sspaeti** [louis030195/obsidian-ava#14]
Even though I copied it from openai.com, it does not recognize my key:
Not sure, do I need to regard something else?

![image](https://user-images.githubusercontent.com/689199/202981734-314137f1-a657-40c4-b7de-59534e7e0be1.png)

**Comment by sudheer82** [comment]
@sspaeti - couple of things to check

- Do you have the API balance and able to use in the OpenAI playground?
- Try re-generating a new key and check
- in Obsidian Open `ctrl`+`shift`+`i` to open the developer tools and check what is the console log right at the moment when new API key is entered into settings

**Comment by sspaeti** [comment]
Thanks so much, @sudheer82; it works now.

I didn't change anything, but now when I open the settings again, it gets the green checkmark:
![image](https://user-images.githubusercontent.com/689199/203745362-f93affc4-abe7-40a9-84c4-320fc26c099d.png)

And after fixing the Templater (creating the script as a file on disk instead of inside the Template itself), it works now!!
Thanks so much; I will try more; this is a useful plugin!
![image](https://user-images.githubusercontent.com/689199/203745766-d50a5be9-154b-44b0-866a-0479d47e8c9d.png)

**Comment by sudheer82** [comment]
@sspaeti - link has a period at the end and its not working.

**Comment by sspaeti** [comment]
Oops, yes, I fixed it above. Thanks.
