### ISSUE TITLE
Ava search & fine-tuning

### ISSUE THREAD

**Issue by louis030195** [louis030195/obsidian-ava#29]
TODOs:

- [ ] metrics / evaluation to know if fine-tuning is worthwhile
- [ ] check if there is an easy way to fine-tune with supervised data collected through user interaction

This is important information that would influence whether we try to implement inference in JS directly (ONNX, TFJS, etc.) which makes it more difficult to fine-tune.

**Comment by louis030195** [comment]
> Performance Comparison
> In our paper [TSDAE](https://arxiv.org/abs/2104.06979) we compare approaches for sentence embedding tasks, and in [GPL](https://arxiv.org/abs/2112.07577) we compare them for semantic search tasks (given a query, find relevant passages). While the unsupervised approach achieve acceptable performances for sentence embedding tasks, they perform poorly for semantic search tasks.

https://www.sbert.net/examples/unsupervised_learning/README.html#performance-comparison

**Comment by louis030195** [comment]
There is also a possibility of computing weak labels through existing links / tags / closeness of notes as for supervised fine-tuning

**Comment by louis030195** [comment]
We could also provide a huggingface hub fine-tuned sentence embedding model good for general purpose Obsidian vault semantic search (or multimodal)

**Comment by louis030195** [comment]
Idea: make a script that each individual can run on its vault to aggregate its public vault data into a huggingface dataset (with some args like filter in/out only what is publicly shareable, like publish: true or some tag/folder)
Then we can fine-tune an Obsidian note embedding model

**Comment by arminta7** [comment]
How hard would it be to add something like this: https://twitter.com/rileytomasek/status/1603854647575384067?s=46&t=if935fDFIydWWmNtFn-R4g

**Comment by louis030195** [comment]
> How hard would it be to add something like this: https://twitter.com/rileytomasek/status/1603854647575384067?s=46&t=if935fDFIydWWmNtFn-R4g

It's unrelated to this issue but we indeed plan to implement a modal or something like https://github.com/scambier/obsidian-omnisearch that search semantically your vault.

Next steps could be to add some large language model post-processing (e.g. summaries, semantic links)

@arminta7 thanks for the feedback :)
