### ISSUE TITLE
How to avoid the installed Python env to be synced by Obsidian Sync?

### ISSUE THREAD

**Issue by wenlzhang** [louis030195/obsidian-ava#30]
Currently, the env would be installed within the plugin folder and would be synced by Obsidian Sync. It would be great if the env can be installed outside the plugin directory, and one can specify the location of the env in the plugin settings.

**Comment by hotkartoffel** [comment]
@wenlzhang yes!

There's two iniatives around this atm:
1. Creating a fully hosted version
2. Moving env in a tmp folder <--- this should come out in the next few days

**Comment by hotkartoffel** [comment]
@wenlzhang we just shipped `2.` if you update to version `2.4.2` it should work

you might want to delete the old `env` manually

**Comment by louis030195** [comment]
Solved IMHO
