### ISSUE TITLE
steps to run under windows?

### ISSUE THREAD

**Issue by davidszp** [louis030195/obsidian-ava#31]
Has anyone successfully run the ava api server under windows? I was getting various errors under python 3.9 when trying to start the server. After installing dependencies, trying to start the server yields 

```
File "[PATH]\my-vault\.obsidian\plugins\ava\semantic\env\lib\site-packages\obsidiantools\md_utils.py", line 273, in _get_md_front_matter_and_content
    return {}, file_string
UnboundLocalError: local variable 'file_string' referenced before assignment
```

Anyone managed to get it to start up?

**Comment by hotkartoffel** [comment]
maybe it would work with WSL


Inside WSL do
```sh
git clone https://github.com/louis030195/obsidian-ava.git
cd obsidian-ava/semantic
sh start-api.sh
```

(then skip the "start api" part in obsidian)

**Comment by louis030195** [comment]
any news?
