### ISSUE TITLE
Wikipedia Links Howto?

### ISSUE THREAD

**Issue by limex** [louis030195/obsidian-ava#32]
Hi,
the "Get Wikipedia Suggestions" is an interesting feature.
But:
* a new Side Panel is created for the links. Wouldnt it be better to add the links at the position of the cursor in the current document?
* Also I can't mark the links to copy them for later use.
* You mention "Press F1",  It's not working on macos (its Command + P there)

Maybe I miss a point here. Please advice or fix.

Nice work so far & BR Günther

![image](https://user-images.githubusercontent.com/1173039/208294083-8f124441-3056-4964-8800-832a7a448641.png)

**Comment by hotkartoffel** [comment]
Yeah, that was my bad, I forgot I had a different shortcut to bring up the commands 😅 (I make my obsidian shortcut be as close to vscode)

Wikipedia is a bit of a broken feature atm (def not it's final form). We'll be bringing it back soon in a way that makes more sense.

Just curious were you just testing it out or did you have a particular use case in mind?

**Comment by louis030195** [comment]
@limex we removed the wikipedia command as you can just do it simply like this:
![image](https://user-images.githubusercontent.com/25003283/210609929-fa833802-f01b-43f3-b75e-ccbc17dd5bd0.png)

cmd+p -> completion

![image](https://user-images.githubusercontent.com/25003283/210609960-4d57c278-3fa2-4db8-83d3-41dad9951be3.png)

**Comment by limex** [comment]
Very nice. That's a very versatile solution. 👍
