### ISSUE TITLE
Plugin is affecting global Obsidian CSS

### ISSUE THREAD

**Issue by zachdoty** [louis030195/obsidian-ava#34]
The plugin is affecting global CSS on Obsidian. See the video:

https://www.loom.com/share/366f677059004eccaa418db48afcb006

**Comment by louis030195** [comment]
@hotkartoffel I noticed also

**Comment by hotkartoffel** [comment]
Looking at it probie, because we're injecting tailwind and that resets some parts of the CSS.

Will have a deeper look today to fix it.

**Comment by hotkartoffel** [comment]
fixed ✅
