### ISSUE TITLE
Bug - Ava does not create the semantic directory

### ISSUE THREAD

**Issue by danrthompson** [louis030195/obsidian-ava#36]
When trying to start the search API, it would silently fail. When I looked at the console, it was giving this error:
```
node:fs:1536 Uncaught (in promise) Error: ENOENT: no such file or directory, stat '/Users/danthompson/Obsidian/Synced Vault/.obsidian/plugins/ava/semantic'
```

I figured that this error was due to it not automatically creating the right directory. I double checked that the issue wasn't due to an old install (I am always searching for obsidian AI plugins so I installed Ava back when it first hit the store). I uninstalled and reinstalled, but it did not help.

Then I manually created the directory `semantic` at `~/Obsidian/Synced Vault/.obsidian/plugins/ava` and running start search API worked.

So I think you need to add a mkdir step, at least when the plugin is installed through the Community Plugin interface.

**Comment by louis030195** [comment]
Thanks for noticing @danrthompson I think for development you need to git clone into "ava" and not "obsidian-ava", we should indeed document this

**Comment by louis030195** [comment]
@danrthompson Now you don't need the local search api :) - works without

**Comment by danrthompson** [comment]
FYI, I didn't clone it from github at all, I installed the plugin from the Obsidian community plugin store.

So if it needs to be cloned into `ava` and not `obsidian-ava`, you might want to set it up to do that in the store installation process

Anyway, thanks so much for the work on this plugin. I also work in AI and was thinking about implementing some of this myself, but was thrilled to see that someone else is applying GPT to Obsidian. I think it could add an enormous amount of value :)
