### ISSUE TITLE
Add the ability to Stop Search API

### ISSUE THREAD

**Issue by danrthompson** [louis030195/obsidian-ava#39]
If I'm not actively using Ava, it would be nice to be able to stop the search API so that it is not running all the time in the background. Especially since it generates a ton of notifications. But also because I assume it is updating the embeddings constantly, which has a cost.

Of course, it's possible to simply disable Ava, but that is more time consuming than a simple command to disable the search API.

**Comment by hotkartoffel** [comment]
<img width="714" alt="Screenshot 2022-12-20 at 11 43 10 PM" src="https://user-images.githubusercontent.com/11430621/208780764-a3ca20bb-5507-4142-8ab8-4393b27fdc0b.png">

We'll be shipping a major iteration soonish (tomorrow or the day after)

**Comment by louis030195** [comment]
Search API is in the cloud now !
