### ISSUE TITLE
Settings UI is Broken + Type Error and Semantic Search Error

### ISSUE THREAD

**Issue by segsmachine** [louis030195/obsidian-ava#42]
On a fresh install, the Ava program has failed to load properly and all features are broken. I'm running the latest plugin version and I have disabled all other community plugins, my custom css, and created an entirely new vault

### **Console Log:**
``` app.js:1 Obsidian Developer Console
app.js:1 Total plugin setup: 753ms
ava: 753ms
plugin:ava:346 Object
plugin:ava:346 e
plugin:ava:346 Ava - Indexing vault with Array(1)
obsidian-ai-c6txy76x2q-uc.a.run.app/v1/search/refresh:1          Failed to load resource: the server responded with a status of 401 ()
plugin:ava:346 Error: Error refreshing semantic search: 
    at Sq (plugin:ava:316:662)
    at async DUt.indexWholeVault (plugin:ava:346:6634)
J3 @ plugin:ava:346
indexWholeVault @ plugin:ava:346
plugin:ava:346 Ava - Unlistening to note events
```
### 
![image](https://user-images.githubusercontent.com/76236580/210025275-65f70253-e686-4657-8cb3-ed3337abc73f.png)

**Comment by segsmachine** [comment]
In addition when "Debug" is enabled, additional settings are visible,

![image](https://user-images.githubusercontent.com/76236580/210025672-82340d48-232a-493e-9fab-7139d7ee2a91.png)

However, there is another error,

```
plugin:ava:286 Refused to set unsafe header "User-Agent"
eval @ plugin:ava:286
C31 @ plugin:ava:285
eval @ plugin:ava:286
bP2.exports @ plugin:ava:286
uS2.exports @ plugin:ava:290
Rq.request @ plugin:ava:290
eval @ plugin:ava:285
eval @ plugin:ava:290
eval @ plugin:ava:290
Promise.then (async)
listFiles @ plugin:ava:290
y @ plugin:ava:293
EC2 @ plugin:ava:10
WC2 @ plugin:ava:10
NC2 @ plugin:ava:10
k61 @ plugin:ava:10
m81 @ plugin:ava:10
eval @ plugin:ava:10
GGt @ plugin:ava:13
F71 @ plugin:ava:10
o$t @ plugin:ava:10
yGt @ plugin:ava:10
iw2 @ plugin:ava:10
```

**Comment by hotkartoffel** [comment]
@segsmachine thanks for the detailed explanation

 the 401 return makes me think it's one of the following issues:
1. Autentication issue: -> to fix logout and log back in
2. Payment issue: -> **we don't have a free plan**, you [need to have  a subscription to make use of this plugin](https://app.anotherai.co/dashboard/pricing)

**Comment by louis030195** [comment]
Thanks for notifying us. We should improve the user feedback in case of error(s).

**Comment by hotkartoffel** [comment]
@segsmachine we added a new free plan as well as improved our error warnings

if you're running the plugin, i suggest you update to the latest version to give it a try
