### ISSUE TITLE
Generate Tags Function

### ISSUE THREAD

**Issue by WickM** [louis030195/obsidian-ava#44]
I wanted to express my appreciation for the Obsidian Plugin you created. 
The Generate Link function has been extremely useful for me, and I've found myself using it extensively. However, I couldn't help but think how even more productive and efficient my workflow could be if there was a similar function for generating tags as well. I believe it would be a valuable addition and I would greatly appreciate it if you could consider adding it. 
Thank you again for your hard work and dedication in creating such a useful tool.

**Comment by hotkartoffel** [comment]
Hi @WickM 

Thanks for the feedback. We’ll include a first iteration of what you describe this week, will ping you when we shipped and would to have your opinion on how to make this even more useful once it’s out.

**Comment by louis030195** [comment]
@WickM Thanks a lot for the support 🚀

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/25003283/213155732-0037303c-5c24-4c8e-995e-fb1b1ede9939.gif)

I just shipped a very simple version of tags generation, you can use it with the command "Ava Tags", or feel free to try Ava getting started :)

![image](https://user-images.githubusercontent.com/25003283/213156218-3500461e-76e2-46d5-9f15-dc74173d4015.png)

**Comment by hotkartoffel** [comment]
We feed gpt-3 your document as well as prompt to make it complete text that follows a certain format.

You can see our exact prompt here:
https://github.com/louis030195/obsidian-ava/blob/e4410887fa71e9276d2a6d3fc6f1696d454e13ba/src/utils.ts#L295
