### ISSUE TITLE
[enahncement]Use gifs instad mov in the readme page

### ISSUE THREAD

**Issue by danieltomasz** [louis030195/obsidian-ava#5]
here oneliner to convert
https://gist.github.com/SheldonWangRJT/8d3f44a35c8d1386a396b9b49b43c385

**Comment by danieltomasz** [comment]
Though the example is quite long, mov has better scrolling but gif is better working on mobile :)

**Comment by louis030195** [comment]
Thanks! Also .mov don't seem to work in Obsidian community plugins UI
DOne :)
