### ISSUE TITLE
"404 DEPLOYMENT_NOT_FOUND" when trying to login

### ISSUE THREAD

**Issue by yvonne-yang** [louis030195/obsidian-ava#72]
Hi, 
I'm on Windows and when I click "connect" to sign up for an Ava account I get a 404 error. Not much logged on the console. Have tried reenabling/reinstalling Ava to no avail. Please let me know if there's anything I can try. Thank you!
![image](https://github.com/louis030195/obsidian-ava/assets/60620007/cbc4d10e-94c8-4ed1-ba73-3bf43f0c5352)

**Comment by muyigege** [comment]
+1

**Comment by louis030195** [comment]
Ava is over
